### ISSUE TITLE
Highlighting gets applied to all files

### ISSUE THREAD

**Issue by Panda4994** [nigelSaysHesHappy/Minecraft-Functions-Syntax-Highlighter#2]
I installed the file in ```~/.local/share/gtksourceview3.0/language-specs/```.
The highlighting worked, but it was also applied to normal txt-files (I assume every file really).

Also let me say that I appreciate this project!
With functions and datapacks taking off in 1.13 a proper syntax highlighter will make life much easier :-)
I also noticed that the highlighting is already outdated with the recent changes to commands. Do you plan to continue this project or know of any alternatives?
Either way, thank you for this project!

**Comment by noglass** [comment]
I'm not sure how I missed this issue for so long... Sorry about that @Panda4994 
I have updated the language file for the current 1.13 syntax, but I haven't resolved the issue of it being the default language file for all types of files yet. I will probably push a new update tomorrow.

**Comment by noglass** [comment]
Resolved plain text files being treated as mcfunction files and updated to full 1.13 syntax in this commit: https://github.com/nigelSaysHesHappy/Minecraft-Functions-Syntax-Highlighter/commit/621be69f85e241bd5f378482c2367f00d3955774

1.14 syntax coming soon
